spring.application.name=SpringSecurity
spring.security.user.name=asad
spring.security.user.password=iamasad
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Qwerty@1234